[2024-06-18T13:21:44.954+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:21:44.974+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_mysql_analytics.insert_into_table manual__2024-06-18T13:21:41.855965+00:00 [queued]>
[2024-06-18T13:21:44.979+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_mysql_analytics.insert_into_table manual__2024-06-18T13:21:41.855965+00:00 [queued]>
[2024-06-18T13:21:44.980+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-18T13:21:44.989+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): insert_into_table> on 2024-06-18 13:21:41.855965+00:00
[2024-06-18T13:21:44.993+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6292) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-18T13:21:44.994+0000] {standard_task_runner.py:63} INFO - Started process 6293 to run task
[2024-06-18T13:21:44.994+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_mysql_analytics', 'insert_into_table', 'manual__2024-06-18T13:21:41.855965+00:00', '--job-id', '748', '--raw', '--subdir', 'DAGS_FOLDER/mysql-analytics-test_dag.py', '--cfg-path', '/tmp/tmpxjulnmh2']
[2024-06-18T13:21:44.995+0000] {standard_task_runner.py:91} INFO - Job 748: Subtask insert_into_table
[2024-06-18T13:21:45.025+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_mysql_analytics.insert_into_table manual__2024-06-18T13:21:41.855965+00:00 [running]> on host 195daacf7793
[2024-06-18T13:21:45.080+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_mysql_analytics' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T13:21:41.855965+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T13:21:41.855965+00:00'
[2024-06-18T13:21:45.081+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:21:45.090+0000] {sql.py:276} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-06-18', 'dag_with_mysql_analytics')
        
[2024-06-18T13:21:45.095+0000] {base.py:84} INFO - Using connection ID 'analytics_localhost' for task execution.
[2024-06-18T13:21:45.100+0000] {base.py:84} INFO - Using connection ID 'analytics_localhost' for task execution.
[2024-06-18T13:21:45.106+0000] {sql.py:487} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-06-18', 'dag_with_mysql_analytics')
        , parameters: None
[2024-06-18T13:21:45.106+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T13:21:45.110+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:21:45.116+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_mysql_analytics, task_id=insert_into_table, run_id=manual__2024-06-18T13:21:41.855965+00:00, execution_date=20240618T132141, start_date=20240618T132144, end_date=20240618T132145
[2024-06-18T13:21:45.167+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T13:21:45.179+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:21:45.181+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
